#!/bin/bash
# ==============================================================================
# USER CONFIGURATION, AUR, AND DOTFILES
# ==============================================================================
set -e

# Security check: Ensure script is run as normal user
if [ "$EUID" -eq 0 ]; then
  echo "[!] ERROR: Do NOT run this script as root (sudo)!"
  echo "-> Run it as your normal user."
  exit 1
fi

# Keep SUDO actives
echo "==> Entry your ROOT passwd for last time :"
sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "==> Starting user configuration..."

# Read hardware profile generated by install script
if [ ! -f /etc/arch_hw_profile.conf ]; then
    echo "[!] ERROR: Hardware profile file not found."
    echo "-> Did you run install_arch.sh first?"
    exit 1
fi
source /etc/arch_hw_profile.conf

# YAY Installation
if ! command -v yay &> /dev/null; then
    echo "==> Installing YAY (AUR Helper)..."
    git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
    cd /tmp/yay-bin
    makepkg -si --noconfirm
    rm -rf /tmp/yay-bin
fi

# ==========================================================================
# USER ENVIRONMENT PROVISIONING (Development & Gaming)
# ==========================================================================
echo "==> Installing Gaming Ecosystem..."
yay -S --noconfirm steam gamescope gamemode mangohud heroic-games-launcher-bin protonup-qt

echo "==> Installing Neovim & LSP Dependencies..."
yay -S --noconfirm \
    neovim nodejs npm unzip wget ripgrep fd fzf \
    cargo go clang make \
    jre-openjdk python python-pip php ghc opam texlive-basic

# HARDWARE ADAPTATION Nvidia
if [ "$HW_DGPU" = "nvidia-legacy" ]; then
	echo "==> NVIDIA Legacy (Pascal) detected : Install nvidia-580xx-dkms from the AUR..."
    sudo pacman -Rdd --noconfirm nvidia-utils 2>/dev/null || true
    yay -S --noconfirm --answerclean All --answerdiff None nvidia-580xx-dkms nvidia-580xx-utils
    yay -S --noconfirm --answerclean All --answerdiff None lib32-nvidia-580xx-utils || true
fi


# ANSI keyboard fix (For T480 or imported laptops missing the ISO `< >` key)
if [ "$HW_KEY_PHYS" = "ansi" ] && [[ "$HW_KEY_SOFT" == *"fr"* ]]; then
    echo "==> ANSI/AZERTY conflict detected: Installing keyboard patch (keyd)..."
    yay -S --noconfirm keyd

    sudo mkdir -p /etc/keyd
    sudo tee /etc/keyd/default.conf > /dev/null <<EOF
[ids]
*
# [rightalt] == AltGr
[rightalt]
# AltGr + "<" -> <
comma = 102nd
# AltGr + ">" -> >
dot = S-102nd
EOF
    sudo systemctl enable --now keyd
fi

# DOTFILES DEPLOYMENT
echo "==> Deploying Dotfiles with GNU Stow..."

rm ~/.bashrc ~/.profile

# Ensure the dotfiles directory exists
if [ ! -d "$HOME/dotfiles" ]; then
    echo "-> Cloning dotfiles repository..."
    git clone https://github.com/CSrubenz/dotfiles.git ~/dotfiles
fi

cd ~/dotfiles

chmod +x deploy.sh
./deploy.sh

# ==========================================================================
# ACTIVATION DES SERVICES (Système & Utilisateur)
# ==========================================================================
echo "==> Enabling critical services..."
sudo systemctl enable --now fstrim.timer # SSD
sudo systemctl enable --now lactd # GPU
systemctl enable --now hyprpolkitagent.service # pop-up
systemctl enable --now syncthing.service

systemctl --user enable --now pipewire.service
systemctl --user enable --now pipewire-pulse.service
systemctl --user enable --now wireplumber.service

echo "[OK] EVERYTHING IS READY ON $HW_HOSTNAME!"
echo "-> Type 'Hyprland' to start your Wayland session."
