#!/bin/bash
# ==============================================================================
# USER CONFIGURATION, AUR, AND DOTFILES
# ==============================================================================
set -e

# Security check: Ensure script is run as normal user
if [ "$EUID" -eq 0 ]; then
  echo "[!] ERROR: Do NOT run this script as root (sudo)!"
  echo "-> Run it as your normal user."
  exit 1
fi

echo "==> Starting user configuration..."

# Read hardware profile generated by install script
if [ ! -f /etc/arch_hw_profile.conf ]; then
    echo "[!] ERROR: Hardware profile file not found."
    echo "-> Did you run install_arch.sh first?"
    exit 1
fi
source /etc/arch_hw_profile.conf

# YAY Installation
if ! command -v yay &> /dev/null; then
    echo "==> Installing YAY (AUR Helper)..."
    git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
    cd /tmp/yay-bin
    makepkg -si --noconfirm
    rm -rf /tmp/yay-bin
fi

# ==========================================================================
# USER ENVIRONMENT PROVISIONING (Development & Gaming)
# ==========================================================================
echo "==> Installing Gaming Ecosystem..."
yay -S --noconfirm steam gamescope gamemode mangohud heroic-games-launcher-bin protonup-qt

echo "==> Installing Neovim & LSP Dependencies..."
yay -S --noconfirm \
    neovim nodejs npm unzip wget ripgrep fd fzf \
    cargo go clang make \
    jre-openjdk python python-pip php ghc opam texlive-basic

# HARDWARE ADAPTATION

if [ "$HW_DGPU" = "nvidia-legacy" ]; then
	echo "==> NVIDIA Legacy (Pascal) detected : Install nvidia-580xx-dkms from the AUR..."
	yay -S --noconfirm nvidia-580xx-dkms nvidia-580xx-utils
fi

# LACT is the thermal/overclocking GUI for AMD cards
if [ "$HW_DGPU" = "amd" ] || [ "$HW_IGPU" = "amd" ]; then
    echo "==> AMD GPU detected: Installing and enabling LACT..."
    yay -S --noconfirm lact
    sudo systemctl enable --now lactd
fi

# ANSI keyboard fix (For T480 or imported laptops missing the ISO `< >` key)
if [ "$HW_KEY_PHYS" = "ansi" ] && [[ "$HW_KEY_SOFT" == *"fr"* ]]; then
    echo "==> ANSI/AZERTY conflict detected: Installing keyboard patch (keyd)..."
    yay -S --noconfirm keyd

    sudo mkdir -p /etc/keyd
    sudo tee /etc/keyd/default.conf > /dev/null <<EOF
[ids]
*
# [rightalt] == AltGr
[rightalt]
# AltGr + "<" -> <
comma = 102nd
# AltGr + ">" -> >
dot = S-102nd
EOF
    sudo systemctl enable --now keyd
fi

# DOTFILES DEPLOYMENT
echo "==> Deploying Dotfiles with GNU Stow..."

# Ensure the dotfiles directory exists
if [ ! -d "$HOME/dotfiles" ]; then
    echo "-> Cloning dotfiles repository..."
    git clone https://github.com/CSrubenz/dotfiles.git ~/dotfiles
fi

cd ~/dotfiles

chmod +x deploy.sh
./deploy.sh

echo "[OK] EVERYTHING IS READY ON $HW_HOSTNAME!"
echo "-> Type 'Hyprland' to start your Wayland session."
